import type { ScoredFinding } from "../prioritize";

export function branchNameFor(repo: string, kind: string, date = new Date()): string {
  const slug = repo.replace(/[^a-zA-Z0-9]+/g, "-").replace(/^-+|-+$/g, "").toLowerCase().slice(0, 40);
  const stamp = date.toISOString().slice(0, 10).replace(/-/g, "");
  const rand = Math.random().toString(36).slice(2, 7);
  return `repo-health/${kind}/${slug}-${stamp}-${rand}`;
}

export function prTitleFor(items: ScoredFinding[]): string {
  if (items.length === 0) return "chore(repo-health): no-op scan";
  const top = items[0]?.finding.title ?? "cleanup";
  return `chore(repo-health): ${top.toLowerCase().slice(0, 60)}${items.length > 1 ? ` (+${items.length - 1})` : ""}`;
}

export function prBodyFor(repo: string, items: ScoredFinding[], runId: string): string {
  const rows = items
    .map((i) => `- [${i.tier}] **${i.finding.severity}** ${i.finding.title} — ${i.finding.description.slice(0, 160)}`)
    .join("\n");
  return [
    `## Repo Health Agent — automated cleanup proposal`,
    ``,
    `**Repo:** ${repo} · **Run:** \`${runId}\``,
    ``,
    `### Findings addressed (${items.length})`,
    rows || "- No findings.",
    ``,
    `### Safety`,
    `- Dry-run previewed; only P0-autofix-safe items included.`,
    `- This PR opens as a DRAFT and cannot merge until a human marks it ready.`,
    `- Secrets (if any) are listed redacted — rotate before merging.`,
    ``,
    `### Merge checklist (all required)`,
    `- [ ] CI is green on this branch`,
    `- [ ] File list matches the approved preview (no extra changes)`,
    `- [ ] Marked ready for review, then merged by a human — never auto-merged`,
    ``,
    `### Rollback`,
    `Revert this PR. Fix-run record: \`${runId}\`.`,
    ``,
    `---`,
    `_Generated by Repo Health Agent. Human review required._`,
  ].join("\n");
}

export function changelogEntryFor(date: string, repo: string, items: ScoredFinding[]): string {
  const lines = items.map((i) => `  - [${i.finding.severity}] ${i.finding.title}`).join("\n");
  return `## ${date} — ${repo}\n${lines || "  - No changes."}\n`;
}
